[versions]
publishGradle = "0.16.0"
arrowGradle = "0.1.0"
kotest = "4.6.2"
kotlin = "1.5.31"

[libraries]
arrow-gradle-noPluginx = { module = "com.javiersc.arrow-gradle:no-plugin", version.ref = "arrowGradle" }
arrow-gradle-pluginx = { module = "com.javiersc.arrow-gradle:plugin", version.ref = "arrowGradle" }
arrow-gradle-precompiled = { module = "com.javiersc.arrow-gradle:precompiled-plugin", version.ref = "arrowGradle" }
gradle-pluginPublish = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "publishGradle" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
